[package]
name = "html-ussd"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
parse-html = "0.4.1"
reqwest = { version = "0.12.15", features = ["blocking"] }
rustyline = "15.0.0"
